version: "3.8"

services:
  dev:
    container_name: angular_dev
    image: angular_dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    ports:
      - 4200:4200 # Angular
      - 9876:9876 # Karma
    volumes:
      - .:/usr/code
      - /usr/code/node_modules
    networks:
      - nestjs-template_dev-net
    command: npm run start:dev

  prod:
    container_name: angular_prod
    image: angular_prod:1.0.0
    restart: always
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run build:nginx

  nginx:
    image: nginx:1.23.1-alpine
    container_name: angular-nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
      - ./nginx/www:/var/www
    ports:
      - 80:80
    depends_on:
      - prod

networks:
  nestjs-template_dev-net:
    external: true
